module.exports = {
  cleanTempDir: 'always',
  incremental: true,
  incrementalFile: 'test/stryker/incremental.json',
  checkers: ['typescript'],
  tsconfigFile: 'tsconfig.json',
  testRunner: 'jest',
  ignoreStatic: true,
  tempDirName: 'stryker-tmp',
  mutate: ['src/**/*.ts', '!**/*.dto.ts', '!**/*.types.ts', '!**/*.module.ts', '!**/*.controller.ts'],
  plugins: ['@stryker-mutator/jest-runner', '@stryker-mutator/typescript-checker'],
  ignorePatterns: [
    '.github/',
    '.husky/',
    '.output/',
    '.run/',
    '.idea/',
    'configs/stryker/',
    'configs/docker/',
    'test/stryker',
    'scripts/',
    '.editorconfig',
    '.npmrc',
    '.nvmrc',
    '.DS_Store',
    '.validate-branch-namerc.json',
    'CHANGELOG.md',
    'LICENSE',
    'package-lock.json',
    'README.md',
  ],
  jest: { configFile: 'configs/jest/jest.config.ts' },
  reporters: ['clear-text', 'progress', 'html', 'json'],
  htmlReporter: { fileName: 'test/stryker/coverage/index.html' },
  jsonReporter: { fileName: 'test/stryker/coverage/mutation.json' },
  disableTypeChecks: '{test,src,lib}/**/*.{js,ts,jsx,tsx,html}',
};
