module.exports = {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/stryker/incremental.json",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  testRunner: "jest",
  ignoreStatic: true,
  mutate: [
    "src/**/*.ts",
    "!src/**/*.dto.ts",
    "!src/**/*.controller.ts",
    "!src/**/*.module.ts",
    "!src/**/*.types.ts",
    "!src/**/*.entity.ts",
    "!src/**/*.constants.ts",
  ],
  plugins: ["@stryker-mutator/jest-runner", "@stryker-mutator/typescript-checker"],
  ignorePatterns: [
    ".github/",
    ".husky/",
    ".output/",
    ".run/",
    ".idea/",
    "configs/stryker/",
    "configs/docker/",
    "tests/stryker/",
    "scripts/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "package-lock.json",
    "README.md",
  ],
  jest: { configFile: "configs/jest/jest-unit.config.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/stryker/coverage/index.html" },
  jsonReporter: { fileName: "tests/stryker/coverage/mutation.json" },
  disableTypeChecks: "{tests,src,lib}/**/*.{js,ts,jsx,tsx,html}",
  thresholds: {
    high: 100,
    low: 44,
    break: 44,
  },
};